apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: (devel)
  name: tridentbackendconfigs.trident.netapp.io
spec:
  group: trident.netapp.io
  names:
    kind: TridentBackendConfig
    listKind: TridentBackendConfigList
    plural: tridentbackendconfigs
    singular: tridentbackendconfig
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
          status:
            properties:
              backendInfo:
                properties:
                  backendName:
                    type: string
                  backendUUID:
                    type: string
                required:
                - backendName
                - backendUUID
                type: object
              deletionPolicy:
                type: string
              lastOperationStatus:
                type: string
              message:
                type: string
              phase:
                type: string
            required:
            - backendInfo
            - deletionPolicy
            - lastOperationStatus
            - message
            - phase
            type: object
        required:
        - spec
        - status
        type: object
    served: true
    storage: true
