apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: (devel)
  name: cdiconfigs.cdi.kubevirt.io
spec:
  group: cdi.kubevirt.io
  names:
    kind: CDIConfig
    listKind: CDIConfigList
    plural: cdiconfigs
    singular: cdiconfig
  scope: Cluster
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              dataVolumeTTLSeconds:
                format: int32
                type: integer
              featureGates:
                items:
                  type: string
                type: array
              filesystemOverhead:
                properties:
                  global:
                    pattern: ^(0(?:\.\d{1,3})?|1)$
                    type: string
                  storageClass:
                    additionalProperties:
                      pattern: ^(0(?:\.\d{1,3})?|1)$
                      type: string
                    type: object
                type: object
              imagePullSecrets:
                items:
                  properties:
                    name:
                      default: ""
                      type: string
                  type: object
                  x-kubernetes-map-type: atomic
                type: array
              importProxy:
                properties:
                  HTTPProxy:
                    type: string
                  HTTPSProxy:
                    type: string
                  noProxy:
                    type: string
                  trustedCAProxy:
                    type: string
                type: object
              insecureRegistries:
                items:
                  type: string
                type: array
              logVerbosity:
                format: int32
                type: integer
              podResourceRequirements:
                properties:
                  claims:
                    items:
                      properties:
                        name:
                          type: string
                      required:
                      - name
                      type: object
                    type: array
                    x-kubernetes-list-map-keys:
                    - name
                    x-kubernetes-list-type: map
                  limits:
                    additionalProperties:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                    type: object
                  requests:
                    additionalProperties:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                    type: object
                type: object
              preallocation:
                type: boolean
              scratchSpaceStorageClass:
                type: string
              tlsSecurityProfile:
                properties:
                  custom:
                    nullable: true
                    properties:
                      ciphers:
                        items:
                          type: string
                        type: array
                      minTLSVersion:
                        enum:
                        - VersionTLS10
                        - VersionTLS11
                        - VersionTLS12
                        - VersionTLS13
                        type: string
                    required:
                    - ciphers
                    - minTLSVersion
                    type: object
                  intermediate:
                    nullable: true
                    type: object
                  modern:
                    nullable: true
                    type: object
                  old:
                    nullable: true
                    type: object
                  type:
                    enum:
                    - Old
                    - Intermediate
                    - Modern
                    - Custom
                    type: string
                type: object
              uploadProxyURLOverride:
                type: string
            type: object
          status:
            properties:
              defaultPodResourceRequirements:
                properties:
                  claims:
                    items:
                      properties:
                        name:
                          type: string
                      required:
                      - name
                      type: object
                    type: array
                    x-kubernetes-list-map-keys:
                    - name
                    x-kubernetes-list-type: map
                  limits:
                    additionalProperties:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                    type: object
                  requests:
                    additionalProperties:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                    type: object
                type: object
              filesystemOverhead:
                properties:
                  global:
                    pattern: ^(0(?:\.\d{1,3})?|1)$
                    type: string
                  storageClass:
                    additionalProperties:
                      pattern: ^(0(?:\.\d{1,3})?|1)$
                      type: string
                    type: object
                type: object
              imagePullSecrets:
                items:
                  properties:
                    name:
                      default: ""
                      type: string
                  type: object
                  x-kubernetes-map-type: atomic
                type: array
              importProxy:
                properties:
                  HTTPProxy:
                    type: string
                  HTTPSProxy:
                    type: string
                  noProxy:
                    type: string
                  trustedCAProxy:
                    type: string
                type: object
              preallocation:
                type: boolean
              scratchSpaceStorageClass:
                type: string
              uploadProxyCA:
                type: string
              uploadProxyURL:
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
