apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: (devel)
  name: helmchartconfigs.helm.cattle.io
spec:
  group: helm.cattle.io
  names:
    kind: HelmChartConfig
    listKind: HelmChartConfigList
    plural: helmchartconfigs
    shortNames:
    - hcc
    singular: helmchartconfig
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              failurePolicy:
                default: reinstall
                enum:
                - abort
                - reinstall
                type: string
              valuesContent:
                type: string
              valuesSecrets:
                items:
                  properties:
                    ignoreUpdates:
                      type: boolean
                    keys:
                      items:
                        type: string
                      type: array
                    name:
                      type: string
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true

